### ISSUE TITLE
一个链接错误

### ISSUE THREAD

**Issue by TCSYANG** [bobwenstudy/zephyr_polling#1]
Compiling  : "platform/windows/windows_driver_serial.c"
Compiling  : "chipset/csr8510/chipset_csr8510.c"
Linking    : "main.exe"
C:/toolchains/SysGCC/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible platform/windows/lib/x86/libusb0.dll when searching for -lusb0
C:/toolchains/SysGCC/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible platform/windows/lib/x86/libusb0.dll when searching for -lusb0
C:/toolchains/SysGCC/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lusb0: No such file or directory
C:/toolchains/SysGCC/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible platform/windows/lib/x86/libusb0.dll when searching for -lusb0
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:238: main.exe] Error 1

**Comment by bobwenstudy** [comment]
因为你windows是amd64的版本，所以需要在make后面加入如下配置《CPU_ARCH=amd64》
如：make all CPU_ARCH=amd64
