### ISSUE TITLE
好像不支持BR/EDR?

### ISSUE THREAD

**Issue by hongshui3000** [bobwenstudy/zephyr_polling#2]
好像不支持BR/EDR
可以参考这个看看
https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-edgefast-bluetooth

**Comment by bobwenstudy** [comment]
> 好像不支持BR/EDR 可以参考这个看看 https://github.com/nxp-mcuxpresso/mcux-sdk-middleware-edgefast-bluetooth

嗯嗯，我看看，目前确实还不支持哦，没那么多时间去做。此外这个是无需os的版本
你那个简单看了下，好像还需要OS支持？

**Comment by bobwenstudy** [comment]
不过确实可以借鉴学习下，谢啦

**Comment by hongshui3000** [comment]
> 

确实需要OS 支持，为RTOS 做了一层抽象
